name: 'Input Actions'
description: |
  This is a template to help you get started with building an action in JavaScript.
  See the README for more information.
inputs:
  access-token:
    description: 'Access token with write access to the repository'
    required: true
